* The data is documented in `input/README.md`.
* TODO ?? Drop "deleted" agency-years from `input/Homologacion.xlsx`.
  Currently, if an agency disappears in a year,
  `Homologacion.xlsx` lists that agency in its first year of non-existence,
  as well as all its years of existence,
  but in its last it appears with a `deleted` value of 1
  (whereas anything that still exists has no `deleted` value).

  This does not seem to add any useful information,
  unless it is used (it currently isn't) as a check on the data,
  to be sure an agency was not omitted by accident.
* TODO
  serial
** DONE Ingest Homologacion.xlsx
** DONE NEXT : create "level 2" values from deuda, funcionamiento and inversion, and delete "total general" rows.
*** PITFALL: If there are three "deuda" matches in a row, they are all the same information, and they have no sector or entity associated; they are totals.
** DONE Make "year, sector, entidad, tipo de gasto, COP" columns.
   serial
*** Extract each sheet to a separate CSV file.
*** Delete "totales generales".
**** Mark all strings matching "total".
**** Verify nothing else matches the string "total".
**** View them.
     They should not include any entities or sectors.
**** Delete them.
*** Create a "level" column.
**** Assign level=0 for anything roughly matching
     funcionamiento, inversion or servicio de la deuda.
**** list all strings for level=0 and for level missing.
     The first should look like it includes no sectors or entities,
     and the latter should look like it only includes those.
**** Create levels 1 and 2.
***** Reverse each year.
***** In each missing level preceded by 0, write a 1.
***** In each missing level preceded by a 1, write a 2.
***** Reverse each year (so now back to normal).
** Adjust for inflation.
** Associate agencies to their codes.
** Make an across-year comparison algorithm.
*** Use Homologacion.xlsx
*** Use an inflation series.
    Present all money values in terms of the later year.
*** Cliassify entities that move according to their later sector
*** If an entity disappears, count it in the sector it would be in today.
*** If a sector disappears, draw it in both phases,
    with a budget of zero later.
** Test data properties.
   No agency should be in more than three rows.
** Verify totals.
   This requires resurrecting the discarded
   agency- and sector-level rows from gastos.
